#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.1.1.111/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null #全局jackson配置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  tomcat:
    uri-encoding: UTF-8
  context-path: /wxshop
wechat:
  #公众号
  mpAppId: wxce0f7960881a2cac
  mpAppSecret: fa27386e007ec04e023a619e41cea46e

